name: Vercel Deployment

on:
  push:
    branches:
      - main
env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}

jobs:
  vercel-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy
        run: vercel -t ${{ env.VERCEL_TOKEN }} -e REACT_APP_API_KEY=${{ env.REACT_APP_API_KEY }}
